name: Makefile CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Initialize and update submodule
      run: |
        git submodule update --init --recursive
      working-directory: ${{ github.workspace }}

    - name: Install dependencies
      run: |
        make
      working-directory: ${{ github.workspace }}

    - name: Run check
      run: |
        make check
      working-directory: ${{ github.workspace }}

    - name: Run distcheck
      run: |
        make distcheck
      working-directory: ${{ github.workspace }}
